GET http://localhost:3003/produtos

###

GET http://localhost:3003/produtos/1

###

POST http://localhost:3003/produtos 
content-type: application/json

{
    "nome": "Notebook",
    "preco": 3200
}

### 

POST http://localhost:3003/produtos 
content-type: application/json

{
    "nome": "Mouse",
    "preco": 32.99
}

###

PUT http://localhost:3003/produtos/2 
content-type: application/json

{
    "nome": "Mouse Gamer",
    "preco": 132.99
}

###

DELETE http://localhost:3003/produtos/1 